### ISSUE TITLE
nombre archivo de bajada.

### ISSUE THREAD

**Issue by mzunigag** [felipinbombin/uoctWebPlatform#1]
El profe me dice que si podiamos agregar al nombre del archivo con los datos que se baja la red a la cual pertenece. ej. Tiempos_red74_2017_ etc

**Comment by felipinbombin** [comment]
hecho! 😛 👍 🎅

**Comment by mzunigag** [comment]
Jajajjaja pero wn anda a carretear era pa otro dia !!! Jajjaja nice, el
profe me tiene cambiabdo unos datos xd
