### ISSUE TITLE
Eliminar unidad cuociente.

### ISSUE THREAD

**Issue by mzunigag** [felipinbombin/uoctWebPlatform#2]
- En el mapa de diferencias porcentuales la información que se despliega sobre un tramo da el valor del cuociente de tiempos pero le pone como unidad s/km. Eso no es así, este número es adimensional. Hay que borrars/km y sugiero dar dos decimales en vez de uno solo

**Comment by mzunigag** [comment]
Además en la leyenda que aparece en el mapa mismo dice % y no es así. No sé si cabrá actual/referencia en vez de %.

Esto me lo mando el profe, pero no es critico.

**Comment by felipinbombin** [comment]
Hecho
